name: flutter_admanager
description: Flutter plugin for Google AdManager/DFP
version: 0.11.2
homepage: https://github.com/adrianlogue/flutter_admanager

environment:
  sdk: ">=2.2.2 <3.0.0"
  # flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.adrianlogue.flutteradmanager
        pluginClass: FlutterAdManagerPlugin
      ios:
        pluginClass: FlutterAdManagerPlugin